version: '3'

# Este archivo está configurado para detectar automáticamente el sistema operativo 
# y montar los volúmenes en la ubicación correcta

services:
  mariadb:
    container_name: mariadb
    build: 
      context: ../requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: always
    env_file:
      - ../../.env

  wordpress:
    container_name: wordpress
    build: 
      context: ../requirements/wordpress
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
        - WP_TITLE=${WP_TITLE}
        - WP_ADMIN_USER=${WP_ADMIN_USER}
        - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
        - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
        - WP_URL=${DOMAIN_NAME}
        - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception_network
    restart: always
    env_file:
      - ../../.env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  nginx:
    container_name: nginx
    build: ../requirements/nginx
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: always
    env_file:
      - ../../.env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress